### ISSUE TITLE
最近我也在研究这个

### ISSUE THREAD

**Issue by ddquk** [guoxiaolongonly/TheBiggerPackage#1]
现在红包好像不太好获取第几个是最大，这个你有什么好的解决方案吗

**Comment by guoxiaolongonly** [comment]
有吧  饿了么的链接上面有个lucky_number=9  这个应该就是最大值了，其余的可以关注一下 
 /restapi/marketing/themes/0/group_sns/{sn}  这个接口

**Comment by ddquk** [comment]
嗯 看到了 这个数字是最大 只是不知道以后饿了么会不会把这个参数处理掉 哈哈

**Comment by ddquk** [comment]
而且这个数字有时候是0，，我起初以为只要大红包被领了就是0，结果有时候我第一个领取也是0。。

**Comment by guoxiaolongonly** [comment]
@ddquk  https://h5.ele.me/restapi/marketing/themes/0/group_sns/2a0b2cac6f3ab41c  尝试一下访问这个地址，你可以看到里面也是有lucky_number这个字段的，这个是饿了么的api，你可以使用你的饿了么红包地址中的sn码替换掉 2a0b2cac6f3ab41c 。

**Comment by ddquk** [comment]
谢谢 我看到了 是可以的 我还想问一下 有没有办法能看到某个红包已领了多少个，，我发现如果我们用小号去领小红包，把大的留给想要领的人。就必须要用小号去领一下红包，才知道还要领几个才到最大，如果我现在有个红包，是第五个最大，已经领到第四个了，我怎么避免第五个红包（大红包）不被小号领走呢？

**Comment by chenluyong** [comment]
这类功能，我已经全部完成。

如果有意愿可以加入我们。

QQ群：370302199

**Comment by guoxiaolongonly** [comment]
@ddquk 我在最近才把功能写完了，在领取红包的时候一定是要去点一下才知道当前红包数量。
当你成功领取红包之后接口会返回 一个json对象 Json对象内部有一个 promotion_records是当前领取过红包的用户列表，你只需要判断这个列表的大小跟幸运红包的位置之间的关系就可以了。

**Comment by ddquk** [comment]
非常感谢 我最近也刚把红包逻辑部分完成 我回头看一下你说的这个

发自我的 iPhone
