### ISSUE TITLE
未获取到正确的cookies信息

### ISSUE THREAD

**Issue by z384647062** [guoxiaolongonly/TheBiggerPackage#2]
登陆qq，绑定好手机号之后仍然提示：未获取到正确的cookies信息

**Comment by guoxiaolongonly** [comment]
你下载最新版本！我更新了！

**Comment by z384647062** [comment]
> 你下载最新版本！我更新了！

刚才试了下最新版，好像在登陆之后验证手机短信然后保存还是会提示未获取到正确的cookies信息，但是接下来去小号界面选择这个小号点击编辑之后再次验证手机号就没有问题。
不知道在第一次验证短信之后是否已经算是成功了，还是需要在编辑里面再次验证手机号才算成功，谢谢

**Comment by guoxiaolongonly** [comment]
@z384647062  保存成功就算成功了没必要编辑，编辑是为了防止cookie过期。你的star呢！！！

**Comment by z384647062** [comment]
> @z384647062 保存成功就算成功了没必要编辑，编辑是为了防止cookie过期。你的star呢！！！

哈哈，点了
